version: "3"
services:
  database:
     image: mysql:latest
     ports: 
       - 5000:3306
     volumes:
       - mysql_data:/var/lib/mysql
     environment:
         MYSQL_ROOT_PASSWORD: root@123
         MYSQL_DATABASE: test1
         
  backend:
     depends_on:
       - database
     build: ./backend
     image: backend-compose:v1.9
     ports: 
       - 4001:9002
       
  frontend:
     depends_on:
       - backend
     build: ./frontend
     image: frontend-compose:v1.1
     expose:
       - 8080
     ports:
       - 8080:80
         
volumes:
  mysql_data:
